version: 2
jobs:
  build:
    docker:
      - image: gcc
    steps:
      - checkout
      - run: make
      - run: mkdir -p /tmp/artifacts
      - run: cp helloWorld /tmp/artifacts/helloWorld
      - store_artifacts:
        path: /tmp/artifacts
